services:
  - type: web
    name: anti-phishing-api
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/health
    envVars:
      - key: PORT
        value: 3000
